ALTER TABLE users ADD COLUMN IF NOT EXISTS github_token VARCHAR(512);
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_username VARCHAR(255);
ALTER TABLE practice_submissions ADD COLUMN IF NOT EXISTS github_pushed BOOLEAN DEFAULT FALSE;
