-- ─────────────────────────────────────────────────────────────────────────────
-- V1: Baseline schema for CodeCombat 2026
--
-- Captured directly from a running production-equivalent database that grew
-- under spring.jpa.hibernate.ddl-auto=update. From this version forward,
-- every schema change must arrive as a new V<n>__*.sql file. ddl-auto is
-- now `validate`.
--
-- Existing deployments (the live DB created by ddl-auto=update before this
-- migration history existed): spring.flyway.baseline-on-migrate=true with
-- spring.flyway.baseline-version=1 means Flyway stamps the current schema
-- as already at V1 in flyway_schema_history (type=BASELINE) and never
-- re-runs this script. Migration begins at V2.
--
-- Fresh installs (CI, brand-new prod): empty schema → no baseline triggered
-- → this script runs from empty and produces the same final schema, so JPA
-- `validate` passes on both paths.
--
-- The IF NOT EXISTS / DO-block guards below are defense-in-depth in case
-- this ever runs against a partially-populated schema during recovery.
--
-- Hibernate's auto-generated constraint names (uk6dotkott..., etc.) are
-- preserved verbatim so an existing DB doesn't see a constraint-name diff
-- when Flyway records the baseline.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.code_snippets (
    id                bigint NOT NULL,
    created_at        timestamp(6) without time zone,
    language          character varying(20) NOT NULL,
    solution_template text NOT NULL,
    updated_at        timestamp(6) without time zone,
    problem_id        bigint NOT NULL,
    CONSTRAINT code_snippets_language_check
        CHECK (((language)::text = ANY ((ARRAY[
            'JAVA'::character varying,
            'CPP'::character varying,
            'PYTHON'::character varying,
            'JAVASCRIPT'::character varying,
            'C'::character varying])::text[])))
);
ALTER TABLE public.code_snippets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.code_snippets_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE IF NOT EXISTS public.contests (
    id          bigint NOT NULL,
    active      boolean NOT NULL,
    description text,
    end_time    timestamp(6) without time zone,
    name        character varying(255) NOT NULL,
    start_time  timestamp(6) without time zone,
    status      character varying(255),
    CONSTRAINT contests_status_check
        CHECK (((status)::text = ANY ((ARRAY[
            'UPCOMING'::character varying,
            'LIVE'::character varying,
            'ENDED'::character varying])::text[])))
);
ALTER TABLE public.contests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contests_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens (
    id          bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token       character varying(255) NOT NULL,
    used        boolean NOT NULL,
    user_id     bigint NOT NULL
);
ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE IF NOT EXISTS public.problems (
    id            bigint NOT NULL,
    active        boolean NOT NULL,
    constraints   text,
    contest_id    bigint,
    description   text,
    example1      text,
    example2      text,
    example3      text,
    images        text,
    input_format  text,
    memory_limit  integer,
    output_format text,
    time_limit    double precision,
    title         character varying(255),
    level         character varying(255) DEFAULT 'MEDIUM'::character varying NOT NULL
);
ALTER TABLE public.problems ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.problems_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE IF NOT EXISTS public.roles (
    id   bigint NOT NULL,
    name character varying(20),
    CONSTRAINT roles_name_check
        CHECK (((name)::text = ANY ((ARRAY[
            'ROLE_USER'::character varying,
            'ROLE_ADMIN'::character varying])::text[])))
);
ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

-- The `scores` table is preserved here ONLY for compatibility with existing
-- deployments. The Score JPA entity has been removed and V2 drops the table.
-- Fresh installs technically don't need it, but creating + dropping in
-- separate migrations keeps the migration log honest about what happened.
CREATE TABLE IF NOT EXISTS public.scores (
    id                 bigint NOT NULL,
    problems_solved    integer,
    total_score        double precision,
    total_time_penalty bigint,
    contest_id         bigint NOT NULL,
    user_id            bigint NOT NULL
);
ALTER TABLE public.scores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scores_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE IF NOT EXISTS public.submissions (
    id                bigint NOT NULL,
    code              text,
    error_message     text,
    language          character varying(255),
    problem_name      character varying(255),
    score             integer,
    status            character varying(255),
    submitted_at      timestamp(6) without time zone,
    test_case_details text,
    test_cases_passed integer,
    time_consumed     double precision,
    total_test_cases  integer,
    user_name         character varying(255),
    user_roll         character varying(255),
    contest_id        bigint,
    problem_id        bigint NOT NULL,
    user_id           bigint NOT NULL,
    CONSTRAINT submissions_language_check
        CHECK (((language)::text = ANY ((ARRAY[
            'JAVA'::character varying,
            'PYTHON'::character varying,
            'CPP'::character varying,
            'C'::character varying,
            'JAVASCRIPT'::character varying])::text[]))),
    CONSTRAINT submissions_status_check
        CHECK (((status)::text = ANY ((ARRAY[
            'PENDING'::character varying,
            'JUDGING'::character varying,
            'AC'::character varying,
            'WA'::character varying,
            'TLE'::character varying,
            'RE'::character varying,
            'CE'::character varying,
            'MLE'::character varying])::text[])))
);
ALTER TABLE public.submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE IF NOT EXISTS public.user_photos (
    id          bigint NOT NULL,
    photo_url   character varying(500) NOT NULL,
    uploaded_at timestamp(6) without time zone,
    user_id     bigint NOT NULL
);
ALTER TABLE public.user_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_photos_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

CREATE TABLE IF NOT EXISTS public.user_problem_solved (
    id            bigint NOT NULL,
    user_id       bigint NOT NULL,
    problem_id    bigint NOT NULL,
    solved_at     timestamp(6) without time zone NOT NULL,
    points_earned integer DEFAULT 0 NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS public.user_problem_solved_id_seq
    START WITH 1 INCREMENT BY 1 CACHE 1;
ALTER SEQUENCE public.user_problem_solved_id_seq OWNED BY public.user_problem_solved.id;
ALTER TABLE ONLY public.user_problem_solved
    ALTER COLUMN id SET DEFAULT nextval('public.user_problem_solved_id_seq'::regclass);

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    id           bigint NOT NULL,
    email        character varying(50) NOT NULL,
    enabled      boolean NOT NULL,
    full_name    character varying(255),
    password     character varying(120) NOT NULL,
    username     character varying(20) NOT NULL,
    total_points integer DEFAULT 0 NOT NULL
);
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq START WITH 1 INCREMENT BY 1 CACHE 1
);

-- ── Primary keys ─────────────────────────────────────────────────────────────
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'code_snippets_pkey') THEN
        ALTER TABLE ONLY public.code_snippets ADD CONSTRAINT code_snippets_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'contests_pkey') THEN
        ALTER TABLE ONLY public.contests ADD CONSTRAINT contests_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'password_reset_tokens_pkey') THEN
        ALTER TABLE ONLY public.password_reset_tokens ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'problems_pkey') THEN
        ALTER TABLE ONLY public.problems ADD CONSTRAINT problems_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'roles_pkey') THEN
        ALTER TABLE ONLY public.roles ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'scores_pkey') THEN
        ALTER TABLE ONLY public.scores ADD CONSTRAINT scores_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'submissions_pkey') THEN
        ALTER TABLE ONLY public.submissions ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_photos_pkey') THEN
        ALTER TABLE ONLY public.user_photos ADD CONSTRAINT user_photos_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_problem_solved_pkey') THEN
        ALTER TABLE ONLY public.user_problem_solved ADD CONSTRAINT user_problem_solved_pkey PRIMARY KEY (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_roles_pkey') THEN
        ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_pkey') THEN
        ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
    END IF;
END $$;

-- ── Unique constraints ───────────────────────────────────────────────────────
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk6dotkott2kjsp8vw4d0m25fb7') THEN
        ALTER TABLE ONLY public.users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk71lqwbwtklmljk3qlsugr1mig') THEN
        ALTER TABLE ONLY public.password_reset_tokens ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_user_problem') THEN
        ALTER TABLE ONLY public.user_problem_solved ADD CONSTRAINT uk_user_problem UNIQUE (user_id, problem_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ukcsarcihf1hr3urpvtho8xxwle') THEN
        ALTER TABLE ONLY public.user_photos ADD CONSTRAINT ukcsarcihf1hr3urpvtho8xxwle UNIQUE (user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ukdlhdgvsldvj5q450tnwltr3rp') THEN
        ALTER TABLE ONLY public.code_snippets ADD CONSTRAINT ukdlhdgvsldvj5q450tnwltr3rp UNIQUE (problem_id, language);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ukr43af9ap4edm43mmtq01oddj6') THEN
        ALTER TABLE ONLY public.users ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ukrpccwdrp1g8vi83awdtfib5m3') THEN
        ALTER TABLE ONLY public.scores ADD CONSTRAINT ukrpccwdrp1g8vi83awdtfib5m3 UNIQUE (user_id, contest_id);
    END IF;
END $$;

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_snippet_problem_lang     ON public.code_snippets       USING btree (problem_id, language);
CREATE INDEX IF NOT EXISTS idx_submission_contest_id    ON public.submissions         USING btree (contest_id);
CREATE INDEX IF NOT EXISTS idx_submission_problem_id    ON public.submissions         USING btree (problem_id);
CREATE INDEX IF NOT EXISTS idx_submission_user_id       ON public.submissions         USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_submission_user_problem  ON public.submissions         USING btree (user_id, problem_id);
CREATE INDEX IF NOT EXISTS idx_ups_problem              ON public.user_problem_solved USING btree (problem_id);
CREATE INDEX IF NOT EXISTS idx_ups_user                 ON public.user_problem_solved USING btree (user_id);

-- ── Foreign keys ─────────────────────────────────────────────────────────────
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk760bgu69957phd7hax608jdms') THEN
        ALTER TABLE ONLY public.submissions
            ADD CONSTRAINT fk760bgu69957phd7hax608jdms FOREIGN KEY (user_id) REFERENCES public.users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkcsxd8nolqrmnpwgulxeqy0is8') THEN
        ALTER TABLE ONLY public.submissions
            ADD CONSTRAINT fkcsxd8nolqrmnpwgulxeqy0is8 FOREIGN KEY (contest_id) REFERENCES public.contests(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkh8ciramu9cc9q3qcqiv4ue8a6') THEN
        ALTER TABLE ONLY public.user_roles
            ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkhfh9dx7w3ubf1co1vdev94g3f') THEN
        ALTER TABLE ONLY public.user_roles
            ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkiolp7fruw10p6qgdv76mvicry') THEN
        ALTER TABLE ONLY public.scores
            ADD CONSTRAINT fkiolp7fruw10p6qgdv76mvicry FOREIGN KEY (contest_id) REFERENCES public.contests(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkj5kbdqokftgx992cx24x3s583') THEN
        ALTER TABLE ONLY public.submissions
            ADD CONSTRAINT fkj5kbdqokftgx992cx24x3s583 FOREIGN KEY (problem_id) REFERENCES public.problems(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkk3ndxg5xp6v7wd4gjyusp15gq') THEN
        ALTER TABLE ONLY public.password_reset_tokens
            ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fkpa9waom3ntotn7gpm2spnsow5') THEN
        ALTER TABLE ONLY public.problems
            ADD CONSTRAINT fkpa9waom3ntotn7gpm2spnsow5 FOREIGN KEY (contest_id) REFERENCES public.contests(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fksk3tdhchykc35f68j4ak33bev') THEN
        ALTER TABLE ONLY public.code_snippets
            ADD CONSTRAINT fksk3tdhchykc35f68j4ak33bev FOREIGN KEY (problem_id) REFERENCES public.problems(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fktkgoiahryd4yntgywbqyyw8o8') THEN
        ALTER TABLE ONLY public.scores
            ADD CONSTRAINT fktkgoiahryd4yntgywbqyyw8o8 FOREIGN KEY (user_id) REFERENCES public.users(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_problem_solved_problem_id_fkey') THEN
        ALTER TABLE ONLY public.user_problem_solved
            ADD CONSTRAINT user_problem_solved_problem_id_fkey
            FOREIGN KEY (problem_id) REFERENCES public.problems(id) ON DELETE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_problem_solved_user_id_fkey') THEN
        ALTER TABLE ONLY public.user_problem_solved
            ADD CONSTRAINT user_problem_solved_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;
